/** @type {import('next').NextConfig} */
export const nextConfig = {
  env: {
    NEXT_SITE_URL: process.env.NEXT_SITE_URL,
    NEXT_GET_USER_URL: process.env.NEXT_GET_USER_URL,
    NEXT_EDIT_USER_URL: process.env.NEXT_EDIT_USER_URL,
    NEXT_DELETE_USER_URL: process.env.NEXT_DELETE_USER_URL,
    NEXT_LOGIN_USER_URL: process.env.NEXT_LOGIN_USER_URL,
    NEXT_REGISTER_USER_URL: process.env.NEXT_REGISTER_USER_URL,
    NEXT_ADD_LINKED_ACCOUNT_URL: process.env.NEXT_ADD_LINKED_ACCOUNT_URL,
    NEXT_DELETE_LINKED_ACCOUNT_URL: process.env.NEXT_DELETE_LINKED_ACCOUNT_URL,
    NEXT_CREATE_ACTIVITY_URL: process.env.NEXT_CREATE_ACTIVITY_URL,
    NEXT_DELETE_ACTIVITY_URL: process.env.NEXT_DELETE_ACTIVITY_URL,
    NEXT_EDIT_ACTIVITY_URL: process.env.NEXT_EDIT_ACTIVITY_URL,
    NEXT_CREATE_CARD_URL: process.env.NEXT_CREATE_CARD_URL,
    NEXT_DELETE_CARD_URL: process.env.NEXT_DELETE_CARD_URL,
    NEXT_EDIT_CARD_URL: process.env.NEXT_EDIT_CARD_URL,
    NEXT_EDIT_CARD_STAGE_URL: process.env.NEXT_EDIT_CARD_STAGE_URL,
    NEXT_RESET_CARD_STAGE_URL: process.env.NEXT_RESET_CARD_STAGE_URL,
    NEXT_REQUEST_REVIEW_CARD_URL: process.env.NEXT_REQUEST_REVIEW_CARD_URL,
    NEXT_ACTIVATE_CARD_URL: process.env.NEXT_ACTIVATE_CARD_URL,
    CI: 'false',
  },
}

export default nextConfig
