version: 2.1
orbs:
  node: circleci/node@7.1.0
  cypress: cypress-io/cypress@3.4.3
jobs:
  run-unit-tests:
    executor:
      name: node/default
      tag: '24.0.0'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install --legacy-peer-deps
      - run:
          name: Run frontend tests
          command: npm run test
  install-and-persist:
    executor:
      name: cypress/default
      node-version: '24.0.0'
    steps:
      - cypress/install:
          install-command: npm install --legacy-peer-deps
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/
  run-integration-tests:
    executor:
      name: cypress/default
      node-version: '24.0.0'
    environment:
      AUTH_SECRET: test-secret
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: Build Next.js app
          command: npm run build
      - cypress/run-tests:
          start-command: npm start
          cypress-command: NODE_ENV=production npx nyc cypress run

workflows:
  test_frontend_app:
    jobs:
      - run-unit-tests:
          name: Run Unit Tests
      - install-and-persist:
          name: Install & Persist To Workspace
      - run-integration-tests:
          name: Run Integration Tests
          requires:
            - Install & Persist To Workspace
