version: 2.1
orbs:
  node: circleci/node@5.2.0
  cypress: cypress-io/cypress@3.3.0
jobs:
  test_frontend:
    executor: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run frontend tests
          command: npm run test
  install-and-persist:
    executor: cypress/default
    steps:
      - cypress/install
      - persist_to_workspace:
          paths:
            - .cache/Cypress
            - project
          root: ~/
  run-tests-in-parallel:
    executor: cypress/default
    parallelism: 4
    steps:
      - attach_workspace:
          at: ~/
      - cypress/run-tests:
          start-command: npm run dev & wait-on http://localhost:3000
          cypress-command: npx nyc cypress run --environment production
            

workflows:
  test_my_app:
    jobs:
      - test_frontend
      - install-and-persist:
          name: Install & Persist To Workspace
      - run-tests-in-parallel:
          name: Run Tests in Parallel
          requires:
            - Install & Persist To Workspace
