version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.4.4
  # heroku: circleci/heroku@1.2.6

jobs:
  test_frontend_and_backend:
    docker:
      - image: cimg/node:18.17-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules, ./backend/node_modules, ./frontend/dashboard/node_modules
      - run:
          command: npm run test
          name: Run frontend and backend tests
          test-results-for: mocha

  build_and_deploy_frontend:
    working_directory: ~/frontend/dashboard
    docker:
      - image: cimg/node:18.17-browsers
    steps:
      - browser-tools/install-browser-tools
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: install dependencies
          command: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules, ./backend/node_modules, ./frontend/dashboard/node_modules
      - run:
          command: |
            npm run build:frontend
            pwd
            npm run deploy --token=$FIREBASE_TOKEN

  build_and_deploy_backend: # this can be any name you choose
    executor: heroku/default
    steps:
      - attach_workspace:
          at: ~/project
      - heroku/deploy-via-git:
          force: true # force push when pushing to the heroku remote, see: https://devcenter.heroku.com/articles/git

workflows:
  test_my_app:
    jobs:
      - test_frontend_and_backend
      - build_and_deploy_frontend:
          requires:
            - test_frontend_and_backend # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main
