#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Run dev in one process and the other commands in another process
npx concurrently --kill-others \
  "npm run dev" \
  "npm run lint && npm test && npm run test:ui && npm run build"